# -*- coding: utf-8 -*-
{
    "name": "School Management System",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/base_menu.xml",
        "views/student_view.xml",
        "views/course_view.xml",
        "views/enrollment_view.xml",
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}