# -*- coding: utf-8 -*-
{
    "name": "Todo App",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base", "mail"],
    "data": [
    "security/ir.model.access.csv",
    "views/base_menu.xml",
    "views/todo_management_views.xml",
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}